openapi: 3.1.0
info:
  title: inventory
  summary: Inventory Management Application
  description: >
    **inventory** is simple *Inventory Management Application* built using
    `MERN` stack for an imaginary store
  version: 1.0.0
  contact:
    name: Manojna
    url: https://github.com/manojnakp/inventory-mern/issues
    email: manojna.gopher@gmail.com
  license:
    name: MIT License
    identifier: MIT
    url: https://spdx.org/licenses/MIT.html
servers:
  - url: /
    description: default value
paths:
  /users:
    $ref: paths/users.yaml
  /users/{uid}:
    $ref: paths/users_{uid}.yaml
  /items:
    $ref: paths/items.yaml
  /items/{itemid}:
    $ref: paths/items_{itemid}.yaml
  /categories:
    $ref: paths/categories.yaml
  /categories/{catid}:
    $ref: paths/categories_{catid}.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      description: use json web tokens in the `Authorization` header
      scheme: bearer
      bearerFormat: jwt
security:
  - bearerAuth: []
tags:
  - name: user
    x-displayName: User
    description: actions related to `users` collection
  - name: item
    x-displayName: Item
    description: actions related to `items` collection
  - name: category
    x-displayName: Category
    description: actions related to `categories` collection
